name: todo_application
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_date_timeline: ^1.1.3
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  fluttertoast: ^8.2.8
  flutter_slidable: ^3.1.1
  font_awesome_flutter: ^10.4.0
  firebase_auth: ^5.3.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/Pacifico/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
