// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCduSQLJZYNY1Q1CgIq49dWVSU_Du0WFws',
    appId: '1:317888180993:web:a8162069bf1c2eb9cbe100',
    messagingSenderId: '317888180993',
    projectId: 'todo-2779d',
    authDomain: 'todo-2779d.firebaseapp.com',
    storageBucket: 'todo-2779d.appspot.com',
    measurementId: 'G-V3V4L2FHPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSHap0LImZQFASXl0ttc4b9qmMc-vRzcM',
    appId: '1:317888180993:android:af6f61f096e4e650cbe100',
    messagingSenderId: '317888180993',
    projectId: 'todo-2779d',
    storageBucket: 'todo-2779d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_eGzG213M-k1fi5jGoZcjGeLgpBOJwsI',
    appId: '1:317888180993:ios:571b0365a09dd686cbe100',
    messagingSenderId: '317888180993',
    projectId: 'todo-2779d',
    storageBucket: 'todo-2779d.appspot.com',
    iosBundleId: 'com.TODo.todoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_eGzG213M-k1fi5jGoZcjGeLgpBOJwsI',
    appId: '1:317888180993:ios:571b0365a09dd686cbe100',
    messagingSenderId: '317888180993',
    projectId: 'todo-2779d',
    storageBucket: 'todo-2779d.appspot.com',
    iosBundleId: 'com.TODo.todoApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCduSQLJZYNY1Q1CgIq49dWVSU_Du0WFws',
    appId: '1:317888180993:web:766a8e7c3858073acbe100',
    messagingSenderId: '317888180993',
    projectId: 'todo-2779d',
    authDomain: 'todo-2779d.firebaseapp.com',
    storageBucket: 'todo-2779d.appspot.com',
    measurementId: 'G-M4QY1NH7E2',
  );
}
